Fix issue 151
atilaneves/reggae pull request #152
Opened 2021-08-10 14:56 UTC by drug007

First valid configuration is stored and if the default config is omitted by some reason (it is a source library for instance) then the stored configuration will be used as default one.

I added the test but failed to incorporate it into the reggae test suit. Should it be an external project like I did or it would better to add it like an unittest?

2021-08-11 16:58 UTC, atilaneves requested changes

2021-08-11 16:58 UTC, atilaneves commented on src/reggae/dub/interop/package.d
> +                output.log("ERROR: Could not get info for configuration \"", config, "\": ", ex.msg);
```d
output.log(`ERROR: Could not get info for configuration "`, config, `": `, ex.msg);
```

No need to escape the double quote, and it's harder to read it that way anyway.

2021-08-16 14:51 UTC, atilaneves commented on src/reggae/dub/interop/package.d
> +                output.log("ERROR: Could not get info for configuration \"", config, "\": ", ex.msg);
There's an error message and it's from the new test in this PR.

2022-01-10 17:25 UTC, atilaneves commented
@drug007 Any news on this?

2022-01-10 18:02 UTC, drug007 commented
Unfortunately, I have neither time nor Windows to find the error preventing the test from passing.

2022-01-10 18:06 UTC, closed without merging